#!/bin/bash

status=$(audtool --playback-status)

if [[ -z "$status" ]]; then
    exit
fi

if [[ "$status" == "playing" ]]; then
    echo -n "  "
else
    echo -n "  "
fi

artist=$(audtool --current-song-tuple-data artist)
title=$(audtool --current-song-tuple-data title)

echo "$artist - $title"
