#!/bin/bash

status=$(audtool --playback-status)

if [[ -z "$status" ]]; then
    exit
fi

if [[ "$status" == "playing" ]]; then
    echo -n "  "
    color="#00b4ff"
else
    echo -n "  "
    color="#ffff00"
fi

artist=$(audtool --current-song-tuple-data artist)
title=$(audtool --current-song-tuple-data title)

echo "$artist - $title"
echo
echo "$color"
