#!/bin/bash

set -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

usage() {
    echo "Usage: $0 [pull | push] <PROGRAM | all>"
    echo
    echo "  PROGRAM:"
    echo "      bash"
    echo "      firefox"
    echo "      git"
    echo "      htop"
    echo "      onboard"
    echo "      roxterm"
    echo
}

config_bash() {
    mkdir -p "$DIR/bash"
    copy "$HOME/.bash_aliases" "$DIR/bash/aliases"
    copy "$HOME/.bash_path"    "$DIR/bash/path"
    copy "$HOME/.bash_prompt"  "$DIR/bash/prompt"
    copy "$HOME/.bashrc"       "$DIR/bash/bashrc"
    copy "$HOME/.profile"      "$DIR/bash/profile"
}

config_firefox() {
    local FFPROFILE="$HOME/.mozilla/firefox/w4rh4wk.default"
    mkdir -p "$FFPROFILE" "$DIR/firefox"
    copy "$FFPROFILE/../profiles.ini" "$DIR/firefox/profiles.ini"
    copy "$FFPROFILE/user.js"         "$DIR/firefox/user.js"
    copy "$FFPROFILE/prefs.js"        "$DIR/firefox/prefs.js"

    # remove some noise
    sed '/app.update.lastUpdateTime/d'       -i "$DIR/firefox/prefs.js"
    sed '/browser.open.lastDir/d'            -i "$DIR/firefox/prefs.js"
    sed '/browser.slowStartup.averageTime/d' -i "$DIR/firefox/prefs.js"
    sed '/browser.slowStartup.samples/d'     -i "$DIR/firefox/prefs.js"
    sed '/buildID/d'                         -i "$DIR/firefox/prefs.js"
    sed '/extensions.bootstrappedAddons/d'   -i "$DIR/firefox/prefs.js"
    sed '/extensions.enabledAddons/d'        -i "$DIR/firefox/prefs.js"
    sed '/extensions.xpiState/d'             -i "$DIR/firefox/prefs.js"
    sed '/lastAppVersion/d'                  -i "$DIR/firefox/prefs.js"
    sed '/lastDailyNotification/d'           -i "$DIR/firefox/prefs.js"
    sed '/lastMaintenance/d'                 -i "$DIR/firefox/prefs.js"
    sed '/lastPlatformVersion/d'             -i "$DIR/firefox/prefs.js"
    sed '/lastupdatetime/d'                  -i "$DIR/firefox/prefs.js"
    sed '/mstone/d'                          -i "$DIR/firefox/prefs.js"
    sed '/nextupdatetime/d'                  -i "$DIR/firefox/prefs.js"
    sed '/pingCountTotal/d'                  -i "$DIR/firefox/prefs.js"
    sed '/pingCountVersion/d'                -i "$DIR/firefox/prefs.js"
    sed '/print/d'                           -i "$DIR/firefox/prefs.js"
    sed '/storage.vacuum.last/d'             -i "$DIR/firefox/prefs.js"
    sed '/telemetry/d'                       -i "$DIR/firefox/prefs.js"
    sed '/toolkit.startup.last_success/d'    -i "$DIR/firefox/prefs.js"
    sed '/version/d'                         -i "$DIR/firefox/prefs.js"
}

config_git() {
    mkdir -p "$DIR/git"
    copy "$HOME/.gitconfig" "$DIR/git/config"
    sed '/token = /d' -i "$DIR/git/config"
}

config_htop() {
    copy "$HOME/.config/htop" "$DIR/htop"
}

config_onboard() {
    if [[ "$1" == "pull" ]]; then
        dconf dump /org/onboard/ > "$DIR/onboard/settings"
    else
        dconf load /org/onboard/ < "$DIR/onboard/settings"
    fi
}

config_roxterm() {
    copy "$HOME/.config/roxterm.sourceforge.net" "$DIR/roxterm"
}

config_all() {
    config_bash "$1"
    config_firefox "$1"
    config_git "$1"
    config_htop "$1"
    config_onboard "$1"
    config_roxterm "$1"
}

if [[ $# -ne 2 || ( "$1" != "pull" && "$1" != "push" ) ]]; then
    usage
    exit 1
else
    if [[ "$1" == "pull" ]]; then
        copy() {
            cp -r -T "$1" "$2"
        }
    else
        copy() {
            cp -i -r -T "$2" "$1"
        }
    fi
fi

"config_$2" "$1"
