#!/bin/bash

set -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

usage() {
    echo "Usage: $0 <pull | push> <PROGRAM | all>"
    echo
    echo "  PROGRAM:"
    echo "      i3"
    echo "      i3blocks"
    echo "      bash"
    echo "      git"
    echo "      rofi"
    echo "      vscode"
    echo "      xresources"
    echo "      scripts"
    echo
}

config_i3() {
    mkdir -p "$DIR/i3"
    copy "$HOME/.config/i3/config" "$DIR/i3/config"
}

config_i3blocks() {
    mkdir -p "$DIR/i3blocks"
    copy "$HOME/.config/i3/i3blocks.conf" "$DIR/i3blocks/i3blocks.conf"
    copy "$HOME/.config/i3/i3blocks"      "$DIR/i3blocks/i3blocks"
}

config_bash() {
    mkdir -p "$DIR/bash"
    copy "$HOME/.bashrc"     "$DIR/bash/bashrc"
    copy "$HOME/.env.sh"     "$DIR/bash/env.sh"
    copy "$HOME/.profile"    "$DIR/bash/profile"
    copy "$HOME/.xsessionrc" "$DIR/bash/xsessionrc"
}

config_compton() {
    mkdir -p "$DIR/compton"
    copy "$HOME/.config/compton.conf" "$DIR/compton/compton.conf"
}

config_git() {
    mkdir -p "$DIR/git"
    copy "$HOME/.gitconfig" "$DIR/git/config"
    sed '/token = /d' -i "$DIR/git/config"
}

config_rofi() {
    mkdir -p "$DIR/rofi"
    copy "$HOME/.config/rofi" "$DIR/rofi"
}

config_vscode() {
    mkdir -p "$HOME/.config/Code" "$DIR/vscode"
    copy "$HOME/.config/Code/User/settings.json"    "$DIR/vscode/settings.json"
    copy "$HOME/.config/Code/User/keybindings.json" "$DIR/vscode/keybindings.json"
    copy "$HOME/.config/Code/User/snippets" "$DIR/vscode/snippets"

    if [[ "$1" == "pull" ]]; then
        code --list-extensions > "$DIR/vscode/extensions.txt"
    elif [[ "$1" == "push" ]]; then
        while read ext; do
            code --install-extension "$ext"
        done < "$DIR/vscode/extensions.txt"
    fi
}

config_xresources() {
    mkdir -p "$DIR/Xresources"
    copy "$HOME/.Xresources" "$DIR/Xresources/Xresources"
}

config_scripts() {
	mkdir -p "$DIR/scripts"
	copy "$HOME/.local/bin/lt"           "$DIR/scripts/lt"
	copy "$HOME/.local/bin/mailto"       "$DIR/scripts/mailto"
	copy "$HOME/.local/bin/rofi-display" "$DIR/scripts/rofi-display"
	copy "$HOME/.local/bin/rofi-remmina" "$DIR/scripts/rofi-remmina"
	copy "$HOME/.local/bin/xdg-open"     "$DIR/scripts/xdg-open"
}

config_all() {
    config_i3 "$1"
    config_i3blocks "$1"
    config_bash "$1"
    config_compton "$1"
    config_git "$1"
    config_vscode "$1"
    config_xresources "$1"
    config_scripts "$1"
}

if [[ $# -ne 2 || ( "$1" != "pull" && "$1" != "push" ) ]]; then
    usage
    exit 1
else
    if [[ "$1" == "pull" ]]; then
        copy() {
            cp -r -T "$1" "$2"
        }
    else
        copy() {
            cp -i -r -T "$2" "$1"
        }
    fi
fi

"config_$2" "$1"
