#!/bin/bash

set -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

usage() {
    echo "Usage: $0 <pull | push> <PROGRAM | all>"
    echo
    echo "  PROGRAM:"
    echo "      bash"
    echo "      git"
    echo "      vscode"
    echo
}

config_bash() {
    mkdir -p "$DIR/bash"
    copy "$HOME/.bashrc"     "$DIR/bash/bashrc"
    copy "$HOME/.env.sh"     "$DIR/bash/env.sh"
    copy "$HOME/.profile"    "$DIR/bash/profile"
    copy "$HOME/.xsessionrc" "$DIR/bash/xsessionrc"
}

config_git() {
    mkdir -p "$DIR/git"
    copy "$HOME/.gitconfig" "$DIR/git/config"
    sed '/token = /d' -i "$DIR/git/config"
}

config_vscode() {
    mkdir -p "$HOME/.config/Code" "$DIR/vscode"
    copy "$HOME/.config/Code/User/settings.json"    "$DIR/vscode/settings.json"
    copy "$HOME/.config/Code/User/keybindings.json" "$DIR/vscode/keybindings.json"
    copy "$HOME/.config/Code/User/snippets" "$DIR/vscode/snippets"

    if [[ "$1" == "pull" ]]; then
        code --list-extensions > "$DIR/vscode/extensions.txt"
    elif [[ "$1" == "push" ]]; then
        while read ext; do
            code --install-extension "$ext"
        done < "$DIR/vscode/extensions.txt"
    fi
}

config_all() {
    config_bash "$1"
    config_git "$1"
    config_vscode "$1"
}

if [[ $# -ne 2 || ( "$1" != "pull" && "$1" != "push" ) ]]; then
    usage
    exit 1
else
    if [[ "$1" == "pull" ]]; then
        copy() {
            cp -r -T "$1" "$2"
        }
    else
        copy() {
            cp -i -r -T "$2" "$1"
        }
    fi
fi

"config_$2" "$1"
