packages_cli=(
    ack-grep
    acpi
    aircrack-ng
    alsa-utils
    apt-file
    autoconf
    automake
    autossh
    binutils
    bison
    build-essential
    cifs-utils
    cmake
    cmatrix
    curl
    dos2unix
    ffmpeg
    flex
    fonts-dejavu
    fonts-hack-ttf
    fonts-inconsolata
    g++
    gcc
    gdb
    git
    gnupg
    haskell-platform
    haskell-stack
    hexer
    htop
    imagemagick
    iperf3
    ipython3
    less
    lftp
    libstdc++-5-doc
    m4
    make
    minicom
    ncdu
    nmap
    openvpn
    p7zip-full
    patch
    pdf2svg
    python3-pep8
    python3-pip
    python3-virtualenv
    recode
    smbclient
    software-properties-common
    tcpdump
    texlive-fonts-extra
    texlive-full
    texlive-xetex
    tmux
    tree
    ttf-ubuntu-font-family
    ubuntu-restricted-extras
    unzip
    vim-nox
    weechat
    wget
    wireshark
    xindy
    xz-utils
    youtube-dl
    zip
)

packages_gui=(
    adwaita-icon-theme
    apt-xapian-index
    audacious
    audacious-plugins
    baobab
    blender
    breeze-cursor-theme
    breeze-icon-theme
    cheese
    chromium-browser
    compton
    dconf-gsettings-backend
    dconf-tools
    dia
    dmz-cursor-theme
    filezilla
    freecad
    gcolor2
    gimp
    gitg
    gksu
    gnome-calculator
    gnome-icon-theme
    gnome-power-manager
    gnome-system-monitor
    gnuplot
    gparted
    indicator-power
    inkscape
    keepassx
    krita
    libappindicator1
    libreoffice
    libreoffice-style-breeze
    lxappearance
    lxpolkit
    mesa-utils
    nemo
    nemo-fileroller
    nitrogen
    okular
    onboard
    openscad
    paman
    pasystray
    pavucontrol
    pavumeter
    qt4-qtconfig
    qtikz
    remmina
    ristretto
    rofi
    steam
    synaptic
    terminator
    thunderbird
    tint2
    transmission
    vlc
    xfce4-power-manager
    xfce4-screenshooter
    xfce4-notifyd
    xfce4-volumed
    xmonad
    xorg
)

packages_without_recommended=(
    lightdm
    lightdm-gtk-greeter
    lightdm-gtk-greeter-settings
)

# ppa:noobslab/icons
# deb http://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_16.04/ /
packages_arc=(
    arc-icons
    arc-theme
    moka-icon-theme
)

# deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
packages_vscode=(code)

# ppa:obsproject/obs-studio
packages_obs=(obs-studio)

