#!/bin/bash

mkdir -p               \
    "$HOME/.config"    \
    "$HOME/.local/bin" \
    "$HOME/Desktop"    \
    "$HOME/Documents"  \
    "$HOME/Downloads"  \
    "$HOME/Music"      \
    "$HOME/Pictures"   \
    "$HOME/Public"     \
    "$HOME/Templates"  \
    "$HOME/Videos"     \


# ------------------------------------------------------------ firefox

declare -A FF_ADDONS
FF_ADDONS=(
    ['activate_per_element']='https://addons.mozilla.org/firefox/downloads/latest/457553/addon-457553-latest.xpi'
    ['cert_patrol.xpi']='https://addons.mozilla.org/firefox/downloads/latest/6415/addon-6415-latest.xpi'
    ['dev_theme.xpi']='https://addons.mozilla.org/firefox/downloads/latest/642786/addon-642786-latest.xpi'
    ['ghostery.xpi']='https://addons.mozilla.org/firefox/downloads/latest/9609/addon-9609-latest.xpi'
    ['google_link_fix.xpi']='https://addons.mozilla.org/firefox/downloads/latest/351740/addon-351740-latest.xpi'
    ['https_everywhere.xpi']='https://addons.mozilla.org/firefox/downloads/latest/229918/addon-229918-latest.xpi'
    ['ublock_origin.xpi']='https://addons.mozilla.org/firefox/downloads/latest/607454/addon-607454-latest.xpi'
)
mkdir -p "$HOME/Desktop/ff_addons"
for name in ${!FF_ADDONS[@]}; do
    wget -O "$HOME/Desktop/ff_addons/$name" "${FF_ADDONS[$name]}"
done


# ------------------------------------------------------------ thunderbird

declare -A TB_ADDONS
TB_ADDONS=(
    ['allow_html_temp.xpi']='https://addons.mozilla.org/thunderbird/downloads/latest/1556/addon-1556-latest.xpi'
    ['enigmail.xpi']='https://addons.mozilla.org/thunderbird/downloads/latest/71/addon-71-latest.xpi'
    ['lightning']='https://addons.mozilla.org/thunderbird/downloads/latest/2313/platform:2/addon-2313-latest.xpi'
    ['manually_sort_folders.xpi']='https://addons.mozilla.org/thunderbird/downloads/latest/15102/addon-15102-latest.xpi'
)
mkdir -p "$HOME/Desktop/tb_addons"
for name in ${!TB_ADDONS[@]}; do
    wget -O "$HOME/Desktop/tb_addons/$name" "${TB_ADDONS[$name]}"
done


# ------------------------------------------------------------ haskell

cabal update
cabal install ghc-mod


# ------------------------------------------------------------ pandoc

cabal install pandoc pandoc-filter


# ------------------------------------------------------------ git completion

wget -O "$HOME/.config/git-completion.bash" 'https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash'
