#!/bin/bash

mkdir -p               \
    "$HOME/.config"    \
    "$HOME/.local/bin" \
    "$HOME/.local/src" \
    "$HOME/Desktop"    \
    "$HOME/Documents"  \
    "$HOME/Downloads"  \
    "$HOME/Music"      \
    "$HOME/Pictures"   \
    "$HOME/Public"     \
    "$HOME/Templates"  \
    "$HOME/Videos"     \

touch "$HOME/.hushlogin"

# ------------------------------------------------------------ firefox

declare -A FF_ADDONS
FF_ADDONS=(
    ['activate_per_element']='https://addons.mozilla.org/firefox/downloads/latest/457553'
    ['cert_patrol']='https://addons.mozilla.org/firefox/downloads/latest/6415'
    ['dev_theme']='https://addons.mozilla.org/firefox/downloads/latest/642786'
    ['foxyproxy']='https://addons.mozilla.org/firefox/downloads/file/400263'
    ['ghostery']='https://addons.mozilla.org/firefox/downloads/latest/9609'
    ['google_link_fix']='https://addons.mozilla.org/firefox/downloads/latest/351740'
    ['https_everywhere']='https://addons.mozilla.org/firefox/downloads/latest/229918'
    ['ublock_origin']='https://addons.mozilla.org/firefox/downloads/latest/607454'
)
mkdir -p "$HOME/Desktop/ff_addons"
for name in ${!FF_ADDONS[@]}; do
    wget -O "$HOME/Desktop/ff_addons/$name.xpi" "${FF_ADDONS[$name]}"
done


# ------------------------------------------------------------ thunderbird

declare -A TB_ADDONS
TB_ADDONS=(
    ['allow_html_temp']='https://addons.mozilla.org/thunderbird/downloads/latest/1556'
    ['enigmail']='https://addons.mozilla.org/thunderbird/downloads/latest/71'
    ['lightning']='https://addons.mozilla.org/thunderbird/downloads/latest/2313'
    ['manually_sort_folders']='https://addons.mozilla.org/thunderbird/downloads/latest/15102'
)
mkdir -p "$HOME/Desktop/tb_addons"
for name in ${!TB_ADDONS[@]}; do
    wget -O "$HOME/Desktop/tb_addons/$name.xpi" "${TB_ADDONS[$name]}"
done


# ------------------------------------------------------------ haskell

cabal update
cabal install ghc-mod


# ------------------------------------------------------------ pandoc

cabal install pandoc pandoc-filter


# ------------------------------------------------------------ git completion

wget -O "$HOME/.config/git-completion.bash" 'https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash'


# ------------------------------------------------------------ bspwm

apt-get -y install xcb libxcb-util0-dev libxcb-ewmh-dev libxcb-randr0-dev \
                   libxcb-icccm4-dev libxcb-keysyms1-dev libxcb-xinerama0-dev \
                   libasound2-dev

git clone 'https://github.com/baskerville/bspwm.git' "$HOME/.local/src/bspwm"
pushd "$HOME/.local/src/bspwm"
make
popd

git clone 'https://github.com/baskerville/sxhkd.git' "$HOME/.local/src/sxhkd"
pushd "$HOME/.local/src/sxhkd"
make
popd


# ------------------------------------------------------------ i3lock

apt-get -y build-dep i3lock

git clone 'https://github.com/Lixxia/i3lock' "$HOME/.local/src/i3lock"
pushd "$HOME/.local/src/i3lock"
make
popd
