#!/usr/bin/env python3

import sys
import subprocess


if __name__ == '__main__':
    subprocess.Popen(['xdg-open'] + sys.argv[1:], stdin=subprocess.PIPE,
                                                  stdout=subprocess.DEVNULL,
                                                  stderr=subprocess.DEVNULL)
