#!/usr/bin/env runhaskell
import Text.Pandoc.JSON
import System.Process

doInclude :: Block -> IO Block
doInclude cb@(CodeBlock (id, classes, namevals) contents) = do
  case "exec" `elem` classes of
       True  -> return . (CodeBlock (id, classes, namevals)) =<< readProcess "bash" [] (contents ++ "\n")
       False -> return cb
doInclude x = return x

main :: IO ()
main = toJSONFilter doInclude
