#!/usr/bin/env runhaskell
import Text.Pandoc.JSON

doInclude :: Block -> IO Block
doInclude cb@(CodeBlock (id, classes, namevals) contents) =
  case "include" `elem` classes of
       True  -> return . (CodeBlock (id, classes, namevals)) =<< readFile contents
       False -> return cb
doInclude x = return x

main :: IO ()
main = toJSONFilter doInclude
