[[ $- != *i* ]] && return

# ------------------------------------------------------------ HISTORY
HISTCONTROL=ignoreboth
HISTSIZE=10000
shopt -s histappend
export PROMPT_COMMAND="history -a"

# ------------------------------------------------------------ BASIC
shopt -s checkwinsize
shopt -s globstar

# ------------------------------------------------------------ EDITOR
export EDITOR=/usr/bin/vim

# ------------------------------------------------------------ PROMPT
__ret_ps1() {
	if [[ $1 != 0 ]]; then
		echo -n "$1 "
	fi
}

NC='\[\e[0m\]'
Black='\[\e[1;30m\]'
Red='\[\e[1;31m\]'
Green='\[\e[1;32m\]'
Yellow='\[\e[1;33m\]'
Blue='\[\e[1;34m\]'
Purple='\[\e[1;35m\]'
Cyan='\[\e[1;36m\]'
White='\[\e[1;37m\]'

PROMPT_DIRTRIM=2
PS1="$Red\$(__ret_ps1 \$?)$Blue\w$Cyan\$(__git_ps1)$Green > $NC"
PS2="$Green> $NC"

# ------------------------------------------------------------ PATH
source "$HOME/.bash_path"

# Node
use-node() {
	export NVM_DIR="$HOME/.nvm"
	source "$NVM_DIR/nvm.sh"
	source "$NVM_DIR/bash_completion"
}

# ------------------------------------------------------------ WINE
export WINEARCH="win32"
export WINEPREFIX="$HOME/.wine32"

# ------------------------------------------------------------ ALIAS
open() {
	(xdg-open "$@" &> /dev/null &)
}

mkcd() {
	mkdir -p "$1" && cd "$1"
}

tssh() {
	ssh -t "$@" "tmux attach-session || tmux new-session"
}

autotssh() {
	autossh -t "$@" "tmux attach-session || tmux new-session"
}

tosh() {
	mosh "$@" tmux attach-session
}

alias l="ls --classify --color=force --group-directories-first --human-readable -l"
alias ll="l --all"
alias ack="ack -r --smart-case --follow"
alias tree="tree -F --dirsfirst"
alias vim="nvim"

# ------------------------------------------------------------ COMPLETION
if [[ -f /usr/share/bash-completion/bash_completion ]]; then
	source /usr/share/bash-completion/bash_completion
fi
